MCKIN-24385 Translations added for 8 languages
mckinseyacademy/xblock-diagnosticfeedback pull request #35
Opened 2020-10-28 13:54 UTC by musmanmalik

Translations added for 8 languages

2020-10-28 13:56 UTC, musmanmalik commented
@msaqib52  Please review this PR.

2020-10-28 20:01 UTC, wasifarbisoft commented on diagnostic_feedback/public/js/translations/ar/textjs.js
> -            (function(global){
Why removing this   "DiagnosticFeedbackXBlockI18N" it is required I guess??

2020-10-29 06:20 UTC, musmanmalik commented on diagnostic_feedback/public/js/translations/ar/textjs.js
> -            (function(global){
I have used the recommended command for compilation where the namespace is not there. I think that was added recently.

2020-10-29 07:13 UTC, msaqib52 commented on diagnostic_feedback/public/js/translations/ar/textjs.js
> -            (function(global){
this namespace should not be removed, seems like namespace attribute is missing in compile command in makefile, please add it there and recompile. https://github.com/mckinseyacademy/xblock-diagnosticfeedback/blob/master/Makefile#L36

2020-10-29 07:24 UTC, msaqib52 requested changes
@musmanmalik these js translations are not being returned by the student_view, so these translations won't work unless we add them to student view.

2020-11-03 11:31 UTC, wasifarbisoft approved these changes

2020-11-03 11:32 UTC, wasifarbisoft commented
@msaqib52 looks good to me! do you see anything :)

2020-11-05 07:58 UTC, msaqib52 commented
@musmanmalik can u install travis on your fork and run the build to see if all the tests are passing.

2020-11-06 11:52 UTC, msaqib52 commented
Build is passing https://travis-ci.com/github/msaqib52/xblock-diagnosticfeedback/jobs/429633061

2020-11-06 11:52 UTC, merged